version: '2'
services:
  fpm:
    image: 'shiftedreality/magento-docker-components-php:7.1-fpm'
    ports:
    - 9000
    links:
    - db
    volumes_from:
    - appdata
    env_file:
    - ./global.env
  cli:
    image: 'shiftedreality/magento-docker-components-php:7.1-cli'
    links:
    - db
    volumes_from:
    - appdata
    env_file:
    - ./global.env
    - ./composer.env
    environment:
    - MAGENTO_ROOT=/var/www/magento
    - M2SETUP_DB_HOST=db
    - M2SETUP_DB_NAME=magento
    - M2SETUP_DB_USER=root
    - M2SETUP_DB_PASSWORD=1234
    - M2SETUP_BASE_URL=http://localhost:8080
  db:
    image: 'mariadb:10'
    ports:
    - 3306
    volumes_from:
    - dbdata
    volumes:
    - ./build/mysql/init:/docker-entrypoint-initdb.d
    environment:
    - MYSQL_ROOT_PASSWORD=1234
  web:
    image: 'shiftedreality/magento-docker-components-nginx:latest'
    ports:
    - '8080:80'
    - '443:443'
    links:
    - fpm
    - db
    volumes_from:
    - appdata
    env_file:
    - ./global.env
    environment:
    - MAGENTO_ROOT=/var/www/magento
  appdata:
    image: alpine
    volumes:
    - magento-sync:/var/www/magento:nocopy
  dbdata:
    image: alpine
    volumes:
    - /var/lib/mysql

volumes:
  magento-sync:
    external: true
